source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NNPlateKeyboard_Example' do
  pod 'NNPlateKeyboard', :path => '../'

  pod 'IQKeyboardManagerSwift'

  target 'NNPlateKeyboard_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
